### ISSUE TITLE
missing backslash in podspec file in documentation

### ISSUE THREAD

**Issue by itsramiel** [mateusz1913/rnbridgingtutorial#19]
While reading the documentation and copying the code from `AppInfoPackage.podspec` in [this step](https://mateusz1913.github.io/rnbridgingtutorial/docs/guides/app-info-module/setup) into my project, I got an error because there are missing backslashes on this line:
`      "HEADER_SEARCH_PATHS" => ""$(PODS_ROOT)/boost"",` as you can see in the image:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/80689446/226121873-72fe4a94-dabe-40e6-a9c7-92f3dcecbde9.png">

**Comment by mateusz1913** [comment]
Fixed in https://github.com/mateusz1913/rnbridgingtutorial/pull/22

**Comment by mateusz1913** [comment]
Fixed in https://github.com/mateusz1913/rnbridgingtutorial/pull/22

**Comment by mateusz1913** [comment]
Fixed in https://github.com/mateusz1913/rnbridgingtutorial/pull/22

**Comment by mateusz1913** [comment]
@itsramiel it was fixed by migrating to new RN `install_modules_dependencies` API

You can revisit [Module Boilerplate](https://mateusz1913.github.io/rnbridgingtutorial/docs/guides/app-info-module/setup) page to check what content should be added to the podspec file
