### ISSUE TITLE
cannot create android codegen files

### ISSUE THREAD

**Issue by itsramiel** [mateusz1913/rnbridgingtutorial#21]
I am following the tutorial step by step.
I have reached [Js specification](https://mateusz1913.github.io/rnbridgingtutorial/docs/guides/app-info-module/js-spec) of the app info module but when I run `yarn codegen:android`, I do not see any generated files in the package's `android/build/generated/source/codegen` directory.

In fact I do not see the build folder at all.

[Here](https://github.com/itsramiel/native-module-tutorial) is the repo of the project which I did following the tutorial. Can you please check it?

**Comment by mateusz1913** [comment]
👋 @itsramiel  thx for raising this bug - it seems that codegen process does not work for not linked packages

[I made improvements](https://github.com/mateusz1913/rnbridgingtutorial/pull/22) to the Getting Started page, where I added a step for running the app on both platforms after bootstrapping it. Also for Android package, I added a minimal boilerplate for `TurboReactPackage` instance (without it, the package cannot be linked and as a result cannot be codegened)

In your case, add the boilerplate [described in source file stubs section](https://mateusz1913.github.io/rnbridgingtutorial/docs/guides/app-info-module/setup#source-files-stubs) to the `app-info-package/android/src/main/java/com/appinfopackage/AppInfoTurboPackage.java` file

You can take a look at this screenshot - this is how the codegenerated build files should look like after you add `TurboReactPackage`

<img width="419" alt="Screenshot 2023-03-19 at 11 24 12" src="https://user-images.githubusercontent.com/25980166/226169095-344c7eec-75d8-4bd0-86f2-5f592e1558ad.png">

**Comment by itsramiel** [comment]
Thanks @mateusz1913. I will revisit the guide next weekend and try again! Thank you!
