### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "AppInfoPackage":

### ISSUE THREAD

**Issue by greatnonso7** [mateusz1913/rnbridgingtutorial#25]
In Podfile:
    AppInfoPackage (from `../app-info-package`)

Specs satisfying the `AppInfoPackage (from `../app-info-package`)` dependency were found, but they required a higher minimum deployment target.

when I try to run the `npx pod-install`

to link them to iOS project.

**Comment by itsramiel** [comment]
go to the apps Podfile and change this `platform :ios, min_ios_version_supported` to `platform :ios, 13.0`

@mateusz1913 I guess this needs to be pointed out in the guide since the podspec requires 13 and above even though I am not sure why the AppInfoPackage requires 13 and above

**Comment by greatnonso7** [comment]
Thank you very much @itsramiel it worked. Would close this now

**Comment by mateusz1913** [comment]
Thx @greatnonso7 & @itsramiel for pointing this out! I added an information for each guide, that mentions the error and a solution to bump the Podfile's min target version

![Screenshot from 2023-04-03 15-02-52](https://user-images.githubusercontent.com/25980166/229519990-315aac04-5df9-476e-9716-c08e0a1e0c16.png)
