### ISSUE TITLE
Cannot find 'RCTPresentedViewController' in scope

### ISSUE THREAD

**Issue by retyui** [mateusz1913/rnbridgingtutorial#45]
I face with `Cannot find 'RCTPresentedViewController' in scope` error, after doing every steps (swift variant) from: https://mateusz1913.github.io/rnbridgingtutorial/docs/guides/save-file-picker-module/ios-imp

I think there is now information about `SaveFilePickerPackage-Bridging-Header.h` that should include 

```cpp
#import <React/RCTUtils.h>
```

**Comment by mateusz1913** [comment]
👋 @retyui don't know why it was omitted, but thx for raising it!
